#!/bin/bash

export ARCH=$(uname -m)
export PWD=$(pwd)
export VAL=$PWD

function is_dir {
  export VAR=$1
  export OUT=$(ls -l | grep 'drw')
  for i in $OUT; do
    if [ i = *$VAR ]; then
      echo "y"
      exit 0
    fi
  done
}

for i in $(ls); do
  if [ $(is_dir i) = y ]; then
    cd $i
    for i2 in $(ls); do
      if [ $i2 == $ARCH ] ; then
        cd $ARCH
        VAL=$(ls)
        PATH=$PATH:/$i/$ARCH/VAL/sbin
      fi
    done
    cd $PWD
  fi
done
