#!/bin/bash

export ARCH=$(uname -m)
export PWD=$(pwd)
export VAL=$PWD

# tests, if a argument is a directory
function is_dir {
  export VAR=$1
  export OUT=$(ls -l | grep 'drw')
  if [[ $OUT == *$VAR* ]]; then
    echo "y"
    exit 0
  fi
}

for i in $(ls); do
  VAL=$(is_dir $i)
  if [[ $VAL == y ]]; then
    cd $i
    for i2 in $(ls); do
      if [[ $i2 == $ARCH ]] ; then
        cd $ARCH
        VAL=$(ls)
        PATH=$PATH:$PWD/$VAL/sbin
      fi
    done
    cd $PWD
  fi
done
echo $PATH
